<?php

namespace Tests\API;

use App\Models\Request;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileCannotBeAdded;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;
use Tests\TestCase;
use Tests\Traits\HasCreatedRequest;
use Tests\Traits\HasNotFoundedRequest;

class GetDetailRequestTest extends TestCase
{
    use HasCreatedRequest, HasNotFoundedRequest;

    /**
     * @var Request
     */
    private Request $request;

    /**
     * @throws FileCannotBeAdded
     * @throws FileDoesNotExist
     * @throws FileIsTooBig
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = $this->getCreatedRequest();
    }

    /**
     * @test Проверка на успешное получение заявки
     */
    public function test_successful_getting_request()
    {
        $uri = "/api/requests/{$this->request->id}";
        $response = $this->getJson($uri);
        $response->assertStatus(200);
    }

    /**
     * @test Проверка на получение несуществующей заявки
     */
    public function test_wrong_getting_not_founded_request()
    {
        $uri = "/api/requests/{$this->getNotFoundedID()}";
        $response = $this->getJson($uri);
        $response->assertStatus(404);
    }
}
