<?php

namespace Tests\WEB;

use App\Models\Request;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileCannotBeAdded;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;
use Tests\TestCase;
use Tests\Traits\HasCreatedRequest;
use Tests\Traits\HasRequestData;

class UpdateRequestTest extends TestCase
{
    use HasCreatedRequest, HasRequestData;

    /**
     * @var Request
     */
    private Request $request;

    /**
     * @throws FileCannotBeAdded
     * @throws FileDoesNotExist
     * @throws FileIsTooBig
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->request = $this->getCreatedRequest();
    }

    /**
     * @test Проверка на успешное открытие страницы редактирования заявки
     */
    public function test_successful_opening_page()
    {
        $uri = "/requests/{$this->request->id}/edit";
        $response = $this->get($uri);
        $response->assertStatus(200);
    }

    /**
     * @test Проверка на успешное обновление заявки
     */
    public function test_successful_updating_request()
    {
        $uri = "/requests/{$this->request->id}";
        $response = $this->patch($uri, $this->getRequestData());
        $response->assertStatus(302);
        $response->assertValid();
    }

    /**
     * @test Проверка на неверное обновление заявки
     */
    public function test_wrong_updating_request()
    {
        $uri = "/requests/{$this->request->id}";
        $response = $this->patch($uri, []);
        $response->assertStatus(302);
        $response->assertInvalid();
    }
}
