# Generated by Django 3.2.7 on 2022-01-14 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_statistic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='statistic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='poll.statistic'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 14, 22, 43, 8, 767208, tzinfo=utc), editable=False),
        ),
    ]
