# Generated by Django 3.2.7 on 2022-01-14 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20220114_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 23, 0, 12, 864583, tzinfo=utc), editable=False),
        ),
    ]
