# Generated by Django 3.2.7 on 2022-01-14 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_statistic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 23, 51, 19, 31106, tzinfo=utc), editable=False),
        ),
    ]
