<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Запускаем транзакцию
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp();
        DB::beginTransaction();
    }

    /**
     * Останавливаем транзакцию, откатываем данные
     *
     * @return void
     */
    protected function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
