theme: jekyll-theme-minimal
title: Algorithms
author: Jegors Čemisovs
email: jegors.cemisovs@outlook.lv
description: > 
  Graph pathfinding algorithms.
  
# social links
twitter_username: rabestro # DO NOT include the @ character, or else the build will fail!
github_username:  rabestro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
