server:
  port: 8081
  servlet:
    context-path: /generator-service
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        exclude: all
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

hibernate:
  hbm2ddl:
    auto: none
  jdbc:
    batch_size: 100
  temp:
    use_jdbc_metadata_defaults: false

  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  format_sql: false
  order_inserts: true
  generate_statistics: false

thread-pool:
  core-size: 1
  max-size: 20

kafka:
  topic:
    name: reports_data
    partition: 1
    partition-factory: 1
  message:
      max-size: 524288000

