spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_generator
    hikari:
      username: postgres
      password: 1
      connection-timeout: 10000
      maximum-pool-size: 10
      poolName: dataGeneratorPool
      idle-timeout: 600000
      max-lifetime: 1800000

kafka:
  producer:
    server: localhost:29092
