const ROOT_HEADER = document.querySelector('.header')
const ROOT_PRODUCTS = document.querySelector('.products')
const ROOT_SHOPPING = document.querySelector('.shopping')
const ROOT_LOADER = document.querySelector('.loader')
const ROOT_ERROR = document.querySelector('.error')
